name: Govulncheck

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install Govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run Govulncheck
      run: govulncheck ./...